In [1]:
import numpy as np
import pandas as pd
dict1={
    "name":["rohan","seema","mahesh","shruti"],
    "marks":[9,55,67,98],
    "city":["Delhi","Jaipur","Rampur","Barilly"]
}
df=pd.DataFrame(dict1)
df

     name  marks     city
0   rohan      9    Delhi
1   seema     55   Jaipur
2  mahesh     67   Rampur
3  shruti     98  Barilly

In [2]:
df.index=[1,2,3,4]
df

     name  marks     city
1   rohan      9    Delhi
2   seema     55   Jaipur
3  mahesh     67   Rampur
4  shruti     98  Barilly

In [3]:
ser=pd.Series(np.random.rand(20))
ser

0     0.980505
1     0.130025
2     0.466175
3     0.806839
4     0.521298
5     0.263410
6     0.592277
7     0.576253
8     0.985831
9     0.833381
10    0.514135
11    0.760891
12    0.544619
13    0.035181
14    0.148150
15    0.274841
16    0.505307
17    0.913835
18    0.131472
19    0.747110
dtype: float64

In [4]:
type(ser)

pandas.Series

In [5]:
newdf=pd.DataFrame(np.random.rand(334,5),index=np.arange(334))
newdf

            0         1         2         3         4
0    0.332951  0.836841  0.971235  0.085400  0.452274
1    0.584286  0.749567  0.859258  0.928626  0.143523
2    0.394433  0.649887  0.275065  0.923299  0.141038
3    0.542664  0.080782  0.344784  0.719179  0.207907
4    0.397398  0.860711  0.265621  0.582216  0.089111
..        ...       ...       ...       ...       ...
329  0.242685  0.680533  0.213112  0.594365  0.930378
330  0.570253  0.249248  0.626525  0.877253  0.441291
331  0.974005  0.067909  0.505143  0.370426  0.905870
332  0.003997  0.928407  0.593935  0.687875  0.664537
333  0.567677  0.648371  0.206321  0.780927  0.503500

[334 rows x 5 columns]

In [6]:
newdf.head(3)

          0         1         2         3         4
0  0.332951  0.836841  0.971235  0.085400  0.452274
1  0.584286  0.749567  0.859258  0.928626  0.143523
2  0.394433  0.649887  0.275065  0.923299  0.141038

In [7]:
newdf.tail(3)

            0         1         2         3         4
331  0.974005  0.067909  0.505143  0.370426  0.905870
332  0.003997  0.928407  0.593935  0.687875  0.664537
333  0.567677  0.648371  0.206321  0.780927  0.503500

In [8]:
newdf.sort_index(axis=0)

            0         1         2         3         4
0    0.332951  0.836841  0.971235  0.085400  0.452274
1    0.584286  0.749567  0.859258  0.928626  0.143523
2    0.394433  0.649887  0.275065  0.923299  0.141038
3    0.542664  0.080782  0.344784  0.719179  0.207907
4    0.397398  0.860711  0.265621  0.582216  0.089111
..        ...       ...       ...       ...       ...
329  0.242685  0.680533  0.213112  0.594365  0.930378
330  0.570253  0.249248  0.626525  0.877253  0.441291
331  0.974005  0.067909  0.505143  0.370426  0.905870
332  0.003997  0.928407  0.593935  0.687875  0.664537
333  0.567677  0.648371  0.206321  0.780927  0.503500

[334 rows x 5 columns]

In [9]:
newdf.drop(0,axis=1)

            1         2         3         4
0    0.836841  0.971235  0.085400  0.452274
1    0.749567  0.859258  0.928626  0.143523
2    0.649887  0.275065  0.923299  0.141038
3    0.080782  0.344784  0.719179  0.207907
4    0.860711  0.265621  0.582216  0.089111
..        ...       ...       ...       ...
329  0.680533  0.213112  0.594365  0.930378
330  0.249248  0.626525  0.877253  0.441291
331  0.067909  0.505143  0.370426  0.905870
332  0.928407  0.593935  0.687875  0.664537
333  0.648371  0.206321  0.780927  0.503500

[334 rows x 4 columns]

In [10]:
newdf.dropna(inplace=True)